### ISSUE TITLE
Model Subunternehmen, Unternehmen und Kontakt

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#29]
Bei Bauleiter Referenz auf Unternehmen ergänzen.

**Comment by janikvonrotz** [comment]
Attribute aus Konakt entfernen. Diese weden von Person geerbt.

**Comment by janikvonrotz** [comment]
Subunternehmen und Kontakt stimmen immer noch nicht. Überprüfe die anderen Klasse wie z.B. der Sachbearbeiter.
Solange es noch Warnungen hat, kann die Klasse nicht verwendet werden.

**Comment by janikvonrotz** [comment]
Beim Unternehmen fehlt noch der CascadeType auf die Adresse.

**Comment by janikvonrotz** [comment]
Exception in thread "main" javax.persistence.RollbackException: java.lang.IllegalStateException: During synchronization
a new object was found through a relationship that was not marked cascade PERSIST: Adresse(id=0, strasse=Zugerstrasse, o
rt=Ort(id=1, plz=8355, ort=Aadorf)).
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:159)

        at ch.issueman.webservice.Controller.persist(Controller.java:25)
        at ch.issueman.webservice.Seed.seed(Seed.java:262)
        at ch.issueman.webservice.Seed.main(Seed.java:59)
Caused by: java.lang.IllegalStateException: During synchronization a new object was found through a relationship that wa
s not marked cascade PERSIST: Adresse(id=0, strasse=Zugerstrasse, ort=Ort(id=1, plz=8355, ort=Aadorf)).
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.discoverUnregisteredNewObjects(Repeatable
WriteUnitOfWork.java:313)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:723)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:15
16)
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitO
fWork.java:278)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169)
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:134)

        ... 3 more
:webservice:seed FAILED
